### ISSUE TITLE
Process: Aggregation

### ISSUE THREAD

**Issue by nicholas-david** [healthysustainablecities/global-indicators#106] opened 2020-12-19 05:01 UTC
@gboeing @carlhiggs 

I am running the aggregation script for 10 cities. The code is not completing though, this is what I am getting

> Process aggregation for hex-level indicators.
> 
> Cities: ['adelaide', 'baltimore', 'bern', 'ghent', 'lisbon', 'mexico_city', 'odense', 'olomouc', 'valencia', 'vic']
> 
> 
> Calculate hex-level indicators weighted by sample points within each city
>   0%|                                                          | 0/10 [00:00<?, ?it/s- 'VirtualXPath'	[XML Path Language - XPath]
>   0%|                                                          | 0/10 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "aggr.py", line 60, in <module>
>     cities[i], config["samplepointResult"], config["hex250"])
>   File "/home/jovyan/work/process/setup_aggr.py", line 37, in calc_hexes_pct_sp_indicators
>     gdf_samplepoint = gpd.read_file(gpkg_input, layer=layer_samplepoint)
>   File "/opt/conda/lib/python3.7/site-packages/geopandas/io/file.py", line 96, in _read_file
>     with reader(path_or_bytes, **kwargs) as features:
>   File "/opt/conda/lib/python3.7/site-packages/fiona/env.py", line 400, in wrapper
>     return f(*args, **kwargs)
>   File "/opt/conda/lib/python3.7/site-packages/fiona/__init__.py", line 257, in open
>     layer=layer, enabled_drivers=enabled_drivers, **kwargs)
>   File "/opt/conda/lib/python3.7/site-packages/fiona/collection.py", line 164, in __init__
>     self.session.start(self, **kwargs)
>   File "fiona/ogrext.pyx", line 549, in fiona.ogrext.Session.start
> ValueError: Null layer: 'samplePointsData'
>  

Do you know why this is happening? I downloaded the GTFS data and the input data from the cloudstor, so I am not sure what is happening. Thanks for the help

**Comment by carlhiggs** [comment] 2020-12-19 05:41
Hi @nicholas-david ,

I reckon double check that the sp.py process has worked as intended before running the aggregation script.  It says "null layer: 
samplePointsData'", which implies that the sp.py process has not worked as intended for at least one of your cities.  I couldn't say why, but if looking at the apparent outputs from sp.py you find that the required inputs to the aggregation script aren't available or otherwise problematic, I think it is best to look at the sp.py script for the issue.  It looks like the required layer hasn't been generated.  Those are my thoughts! If that is the case, try deleting the outputs for at least one of the cities and re-run the setup configuration and the sp.py script and pay close attention to the output in case there are any clues why this hasn't been generated.  Good luck!  Carl

**Comment by carlhiggs** [comment] 2020-12-19 05:42
It might be worth closing or renaming the issue if it doesn't relate to aggregation

**Closed as completed** 2020-12-27 19:16 UTC
